In [3]:
import pandas as pd
import nltk
from sklearn.feature_extraction import DictVectorizer
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

,sentence,words,pos,tags
0,"Paid Rs.162 to Compass101153Pos1 at Mar 16, 2...",Paid,NNP,NaN
1,NaN,Rs.162,NNP,AMT
2,NaN,to,TO,NaN
3,NaN,Compass101153Pos1,NNP,NaN
4,NaN,at,IN,NaN

In [45]:
df = df.fillna(value="")
feature_df = df.drop(['tags', 'sentence','words'],axis=1)
v = DictVectorizer(sparse=False)
feature_df.head()

   pos
0  NNP
1  NNP
2   TO
3  NNP
4   IN

In [53]:
X = v.fit_transform(feature_df.to_dict('records'))
y = df.tags.values
classes = np.unique(y)
classes = classes.tolist()
classes
y

array(['', 'AMT', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', 'AMT', '', '', 'AMT', '', '', 'AMT', '',
       '', '', '', 'AMT', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', 'AMT', '', '', 'AMT', '', '', 'AMT', '', '', '', '',
       'AMT', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       'AMT', '', '', 'AMT', '', '', 'AMT', '', '', '', '', 'AMT', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', 'AMT', '', '',
       'AMT', '', '', 'AMT', '', '', '', '', 'AMT', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', 'AMT'], dtype=object)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)
X_train.shape, y_train.shape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
per = Perceptron(verbose=10, n_jobs=-1, max_iter=5)
per.partial_fit(X_train, y_train, classes)

new_classes = classes.copy()
new_classes.pop()

print(classification_report(y_pred=per.predict(X_test), y_true=y_test, labels=new_classes))
print(accuracy_score(y_test, per.predict(X_test)))

-- Epoch 1
Norm: 1.73, NNZs: 3, Bias: -1.000000, T: 87, Avg. loss: 0.218391
Total training time: 0.00 seconds.
              precision    recall  f1-score   support

                   0.86      1.00      0.93        38

   micro avg       0.86      1.00      0.93        38
   macro avg       0.86      1.00      0.93        38
weighted avg       0.86      1.00      0.93        38

0.8636363636363636

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)